proposed changes
advisr-io/advisr-applicant-project pull request #1
Opened 2023-08-10 21:33 UTC by jonstorer

I made some changes to the existing applicant project that force situations in order to see how the applicant will handle each.

## Objectives

1. When I load the app I see a list of businesses that includes the Business Name, Category, Number of Campaigns, and Average Campaign Budget
2. When I click on a column header, the list of businesses sorts
3. When I enter text in a search box, the list of businesses filters by name
4. When I click a business's name, I am on a new page.
   1. At the top, I see the business's name
   1. I see the business's details
   2. I see the business's location on a map (google maps or any other map utility)
   3. I see a list of the business's campaigns that includes the Name and Budget
      1. When I click on the column header, the list of campaigns sorts
      2. When I enter text in a search box, the list of campaigns filters by name

## Rubric

### Backed End Considerations

##### json files
- Is the loaded from the json files and preprocessed?
- Is it reformatted for use?

##### "List" Businesses endpoint?
- Supports sorting?
- Supports filtering?
- Supports pagination?
- Data for the list of businesses or business details or both?
- Has the data been restructured for api presentation (or is it a "database dump")?
- Where is the "average campaign budget" calcualted?
- Is sensative data scrubbed from api responses?

##### Is there a "Show" Business endpoint?
- Is the data in the show endpoint different than a single record from the list endpoint?
- Is the data in the "show" endpoint an augmentation of the data in the "list" endpoint for a single record?
- Has the data been restructured for api presentation (or is it a "database dump")?
- Where is the "average campaign budget" calcualted?
- Is sensative data scrubbed from api responses?

#### Front End

##### list of businesses
- Does the submission show all the required data?
- Does the submission use a table to show businesses? (Or other appropriate structure)
- Where is the average campaign budget calcualted?
- Is the long list of businesses paginated ? (Or another appropriate long list strategy)
- Does the first click of a header sort the data? Does the 2nd reverse the sort?
- Does filtering the list via the search box filter data well? In the front end? Sent to the sever? Is there a delay sending to the server?
- Does clicking a business name navigate to a new url (ex business/:id)?

##### details of a business

- Does the submission use routing to render a different view for the details page?
- Does the submission show all the required data?
- Is the calculation of the Average Campaign Budget reused (shared in the fe or be) or is the calculation duplicated? 
- Does the submission use an easy map library (component?) to show the location?
- Does the table sorting / filtering / rendering use components to share the logic between the list of businesses and campaigns?

2023-08-17 18:04 UTC, dpowers-advisr requested changes
Just some wording things and a typo

2023-08-17 18:04 UTC, dpowers-advisr commented on README.md
> +4. When I click a business's name, I am take to a new page.
4. When I click a business's name, I am redirected to a new page.

2023-08-17 18:04 UTC, dpowers-advisr commented on README.md
> +We will schedule time for you to come in and talk us through your completed project.
We will schedule time for you to talk us through your completed project.

2023-08-17 19:35 UTC, kusala-w approved these changes
Looks good

2023-08-17 21:00 UTC, jonstorer commented on README.md
> +4. When I click a business's name, I am take to a new page.
@dpowers-advisr good call out. I'm going update this to be at least correct english. However, I'm trying to be soft in my language here. I don't want to use to leading of language to push them into using routing. I want them to extract the requirement from the "good design patterns" they already have. That said, does this language suffice?

```
4. When I click a business's name, I am taken to a new page.
```

2023-08-18 14:08 UTC, dpowers-advisr commented on README.md
> +4. When I click a business's name, I am take to a new page.
Yup looks good to me

2023-08-18 14:09 UTC, dpowers-advisr approved these changes
🚀

2023-08-21 16:59 UTC, JaimeNufio commented
Looks good 👍

2023-08-21 18:44 UTC, closed without merging